// export const INJECTABLE_METADATA_KEY = Symbol('INJECTABLE_KEY');
// export const SCOPE_METADATA_KEY = Symbol('SCOPE_KEY');
// export const FACTORY_METADATA_KEY = Symbol('FACTORY_KEY');
// export const INJECT_METADATA_KEY = Symbol('INJECT_KEY');
// export const CONTAINER_ID = Symbol("CONTAINER")
// export const POSTCONSTRUCT_SYNC_METADATA_KEY = Symbol('POSTCONSTRUCT_SYNC_KEY');
// export const POSTCONSTRUCT_ASYNC_METADATA_KEY = Symbol('POSTCONSTRUCT_ASYNC_KEY');
// export const OPTIONAL_METADATA_KEY = Symbol('OPTIONAL_KEY');

export const INJECTABLE_METADATA_KEY = "INJECTABLE_KEY";
export const SCOPE_METADATA_KEY = "SCOPE_KEY";
export const FACTORY_METADATA_KEY = "FACTORY_KEY";
export const INJECT_METADATA_KEY = "INJECT_KEY";
export const INJECT_METADATA_PROP_KEY = "INJECT_PROP_KEY";
export const CONTAINER_ID = "CONTAINER"
export const POSTCONSTRUCT_SYNC_METADATA_KEY = "POSTCONSTRUCT_SYNC_KEY";
export const POSTCONSTRUCT_ASYNC_METADATA_KEY = "POSTCONSTRUCT_ASYNC_KEY";
export const DISPOSE_SYNC_METADATA_KEY = "DISPOSE_SYNC_KEY";
export const DISPOSE_ASYNC_METADATA_KEY = "DISPOSE_ASYNC_KEY";
export const OPTIONAL_METADATA_KEY = "OPTIONAL_KEY";


export const REFLECT_PARAMS = 'design:paramtypes';
export const REFLECT_RETURN = 'design:returntype';
export const REFLECT_TYPE = 'design:type';
